#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("WeightTracker.Resource", IsApplication=true)]

namespace WeightTracker
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f060000
			public const int ChartDataArray = 2131099648;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f040009
			public const int amount_changed_left_margin = 2130968585;
			
			// aapt resource value: 0x7f04000a
			public const int amount_changed_width = 2130968586;
			
			// aapt resource value: 0x7f04000c
			public const int date_label_width = 2130968588;
			
			// aapt resource value: 0x7f04000d
			public const int date_picker_height = 2130968589;
			
			// aapt resource value: 0x7f04000b
			public const int date_picker_width = 2130968587;
			
			// aapt resource value: 0x7f040004
			public const int display_header_label_value_width = 2130968580;
			
			// aapt resource value: 0x7f040003
			public const int display_header_label_width = 2130968579;
			
			// aapt resource value: 0x7f040005
			public const int edit_text_height = 2130968581;
			
			// aapt resource value: 0x7f040006
			public const int edit_text_left_margin = 2130968582;
			
			// aapt resource value: 0x7f040008
			public const int edit_text_text_size = 2130968584;
			
			// aapt resource value: 0x7f040007
			public const int edit_text_width = 2130968583;
			
			// aapt resource value: 0x7f040001
			public const int header_label_height = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int header_label_text_size = 2130968576;
			
			// aapt resource value: 0x7f040002
			public const int header_label_width = 2130968578;
			
			// aapt resource value: 0x7f040012
			public const int list_view_height = 2130968594;
			
			// aapt resource value: 0x7f040013
			public const int list_view_top_margin = 2130968595;
			
			// aapt resource value: 0x7f040018
			public const int row_total_change_height = 2130968600;
			
			// aapt resource value: 0x7f040017
			public const int row_total_change_left_margin = 2130968599;
			
			// aapt resource value: 0x7f040014
			public const int row_weight_change_height = 2130968596;
			
			// aapt resource value: 0x7f040015
			public const int row_weight_change_left_margin = 2130968597;
			
			// aapt resource value: 0x7f040016
			public const int row_weight_change_top_margin = 2130968598;
			
			// aapt resource value: 0x7f040010
			public const int save_button_height = 2130968592;
			
			// aapt resource value: 0x7f04000e
			public const int save_button_left_margin = 2130968590;
			
			// aapt resource value: 0x7f04000f
			public const int save_button_top_margin = 2130968591;
			
			// aapt resource value: 0x7f040011
			public const int save_button_width = 2130968593;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int trash = 2130837505;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f080026
			public const int AbsChange = 2131230758;
			
			// aapt resource value: 0x7f080023
			public const int AbsTextBox = 2131230755;
			
			// aapt resource value: 0x7f08003f
			public const int ActionViewCharts = 2131230783;
			
			// aapt resource value: 0x7f080002
			public const int BarChartDataSpinner = 2131230722;
			
			// aapt resource value: 0x7f080003
			public const int BarChartLinearLayout = 2131230723;
			
			// aapt resource value: 0x7f080022
			public const int ChestChange = 2131230754;
			
			// aapt resource value: 0x7f08001f
			public const int ChestTextBox = 2131230751;
			
			// aapt resource value: 0x7f080019
			public const int Date = 2131230745;
			
			// aapt resource value: 0x7f080014
			public const int DisplayAbs = 2131230740;
			
			// aapt resource value: 0x7f08000e
			public const int DisplayChest = 2131230734;
			
			// aapt resource value: 0x7f080006
			public const int DisplayHips = 2131230726;
			
			// aapt resource value: 0x7f080008
			public const int DisplayLeftArm = 2131230728;
			
			// aapt resource value: 0x7f08000f
			public const int DisplayLeftCalf = 2131230735;
			
			// aapt resource value: 0x7f080009
			public const int DisplayLeftThigh = 2131230729;
			
			// aapt resource value: 0x7f08000b
			public const int DisplayRightArm = 2131230731;
			
			// aapt resource value: 0x7f080012
			public const int DisplayRightCalf = 2131230738;
			
			// aapt resource value: 0x7f08000c
			public const int DisplayRightThigh = 2131230732;
			
			// aapt resource value: 0x7f080016
			public const int DisplayTotalSizeChange = 2131230742;
			
			// aapt resource value: 0x7f080018
			public const int DisplayTotalWeightChange = 2131230744;
			
			// aapt resource value: 0x7f080011
			public const int DisplayWaist = 2131230737;
			
			// aapt resource value: 0x7f080005
			public const int DisplayWeight = 2131230725;
			
			// aapt resource value: 0x7f080028
			public const int HipsChange = 2131230760;
			
			// aapt resource value: 0x7f080025
			public const int HipsTextBox = 2131230757;
			
			// aapt resource value: 0x7f08001e
			public const int LeftArmChange = 2131230750;
			
			// aapt resource value: 0x7f08001b
			public const int LeftArmTextBox = 2131230747;
			
			// aapt resource value: 0x7f080031
			public const int LeftCalfChange = 2131230769;
			
			// aapt resource value: 0x7f08002d
			public const int LeftCalfTextBox = 2131230765;
			
			// aapt resource value: 0x7f08002b
			public const int LeftThighChange = 2131230763;
			
			// aapt resource value: 0x7f080027
			public const int LeftThighTextBox = 2131230759;
			
			// aapt resource value: 0x7f080004
			public const int MeasurementBarChart = 2131230724;
			
			// aapt resource value: 0x7f080037
			public const int MeasurementsListView = 2131230775;
			
			// aapt resource value: 0x7f080020
			public const int RightArmChange = 2131230752;
			
			// aapt resource value: 0x7f08001d
			public const int RightArmTextBox = 2131230749;
			
			// aapt resource value: 0x7f080033
			public const int RightCalfChange = 2131230771;
			
			// aapt resource value: 0x7f080030
			public const int RightCalfTextBox = 2131230768;
			
			// aapt resource value: 0x7f08002e
			public const int RightThighChange = 2131230766;
			
			// aapt resource value: 0x7f08002a
			public const int RightThighTextBox = 2131230762;
			
			// aapt resource value: 0x7f080039
			public const int RowDate = 2131230777;
			
			// aapt resource value: 0x7f080038
			public const int RowDeleteButton = 2131230776;
			
			// aapt resource value: 0x7f08003b
			public const int RowTotalChange = 2131230779;
			
			// aapt resource value: 0x7f08003c
			public const int RowWeightChange = 2131230780;
			
			// aapt resource value: 0x7f080035
			public const int SaveButton = 2131230773;
			
			// aapt resource value: 0x7f080024
			public const int WaistChange = 2131230756;
			
			// aapt resource value: 0x7f080021
			public const int WaistTextBox = 2131230753;
			
			// aapt resource value: 0x7f08001c
			public const int WeightChange = 2131230748;
			
			// aapt resource value: 0x7f08001a
			public const int WeightTextBox = 2131230746;
			
			// aapt resource value: 0x7f080000
			public const int linearLayout1 = 2131230720;
			
			// aapt resource value: 0x7f08002c
			public const int linearLayout10 = 2131230764;
			
			// aapt resource value: 0x7f08002f
			public const int linearLayout11 = 2131230767;
			
			// aapt resource value: 0x7f080032
			public const int linearLayout12 = 2131230770;
			
			// aapt resource value: 0x7f080034
			public const int linearLayout13 = 2131230772;
			
			// aapt resource value: 0x7f080036
			public const int linearLayout14 = 2131230774;
			
			// aapt resource value: 0x7f080007
			public const int linearLayout2 = 2131230727;
			
			// aapt resource value: 0x7f08000a
			public const int linearLayout3 = 2131230730;
			
			// aapt resource value: 0x7f08000d
			public const int linearLayout4 = 2131230733;
			
			// aapt resource value: 0x7f080010
			public const int linearLayout5 = 2131230736;
			
			// aapt resource value: 0x7f080013
			public const int linearLayout6 = 2131230739;
			
			// aapt resource value: 0x7f080015
			public const int linearLayout7 = 2131230741;
			
			// aapt resource value: 0x7f080017
			public const int linearLayout8 = 2131230743;
			
			// aapt resource value: 0x7f080029
			public const int linearLayout9 = 2131230761;
			
			// aapt resource value: 0x7f080001
			public const int textView1 = 2131230721;
			
			// aapt resource value: 0x7f08003d
			public const int textView2 = 2131230781;
			
			// aapt resource value: 0x7f08003a
			public const int textView3 = 2131230778;
			
			// aapt resource value: 0x7f08003e
			public const int textView5 = 2131230782;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int ChartViewer = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int DisplayMeasurement = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Main = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int MeasurementRow = 2130903043;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f070000
			public const int MainMenu = 2131165184;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050000
			public const int app_name = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int bar_spinner_prompt = 2131034113;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
