#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("WeightTracker.Resource", IsApplication=true)]

namespace WeightTracker
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f040007
			public const int amount_changed_left_margin = 2130968583;
			
			// aapt resource value: 0x7f040009
			public const int date_label_width = 2130968585;
			
			// aapt resource value: 0x7f04000a
			public const int date_picker_height = 2130968586;
			
			// aapt resource value: 0x7f040008
			public const int date_picker_width = 2130968584;
			
			// aapt resource value: 0x7f040003
			public const int edit_text_height = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int edit_text_left_margin = 2130968580;
			
			// aapt resource value: 0x7f040006
			public const int edit_text_text_size = 2130968582;
			
			// aapt resource value: 0x7f040005
			public const int edit_text_width = 2130968581;
			
			// aapt resource value: 0x7f040001
			public const int header_label_height = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int header_label_text_size = 2130968576;
			
			// aapt resource value: 0x7f040002
			public const int header_label_width = 2130968578;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060015
			public const int AbsChange = 2131099669;
			
			// aapt resource value: 0x7f060011
			public const int AbsTextBox = 2131099665;
			
			// aapt resource value: 0x7f06000f
			public const int ChestChange = 2131099663;
			
			// aapt resource value: 0x7f06000b
			public const int ChestTextBox = 2131099659;
			
			// aapt resource value: 0x7f060002
			public const int Date = 2131099650;
			
			// aapt resource value: 0x7f060018
			public const int HipsChange = 2131099672;
			
			// aapt resource value: 0x7f060014
			public const int HipsTextBox = 2131099668;
			
			// aapt resource value: 0x7f060009
			public const int LeftArmChange = 2131099657;
			
			// aapt resource value: 0x7f060005
			public const int LeftArmTextBox = 2131099653;
			
			// aapt resource value: 0x7f060021
			public const int LeftCalfChange = 2131099681;
			
			// aapt resource value: 0x7f06001d
			public const int LeftCalfTextBox = 2131099677;
			
			// aapt resource value: 0x7f06001b
			public const int LeftThighChange = 2131099675;
			
			// aapt resource value: 0x7f060017
			public const int LeftThighTextBox = 2131099671;
			
			// aapt resource value: 0x7f06000c
			public const int RightArmChange = 2131099660;
			
			// aapt resource value: 0x7f060008
			public const int RightArmTextBox = 2131099656;
			
			// aapt resource value: 0x7f060023
			public const int RightCalfChange = 2131099683;
			
			// aapt resource value: 0x7f060020
			public const int RightCalfTextBox = 2131099680;
			
			// aapt resource value: 0x7f06001e
			public const int RightThighChange = 2131099678;
			
			// aapt resource value: 0x7f06001a
			public const int RightThighTextBox = 2131099674;
			
			// aapt resource value: 0x7f060025
			public const int SaveButton = 2131099685;
			
			// aapt resource value: 0x7f060012
			public const int WaistChange = 2131099666;
			
			// aapt resource value: 0x7f06000e
			public const int WaistTextBox = 2131099662;
			
			// aapt resource value: 0x7f060006
			public const int WeightChange = 2131099654;
			
			// aapt resource value: 0x7f060004
			public const int WeightTextBox = 2131099652;
			
			// aapt resource value: 0x7f060000
			public const int linearLayout1 = 2131099648;
			
			// aapt resource value: 0x7f06001c
			public const int linearLayout10 = 2131099676;
			
			// aapt resource value: 0x7f06001f
			public const int linearLayout11 = 2131099679;
			
			// aapt resource value: 0x7f060022
			public const int linearLayout12 = 2131099682;
			
			// aapt resource value: 0x7f060024
			public const int linearLayout13 = 2131099684;
			
			// aapt resource value: 0x7f060003
			public const int linearLayout2 = 2131099651;
			
			// aapt resource value: 0x7f060007
			public const int linearLayout3 = 2131099655;
			
			// aapt resource value: 0x7f06000a
			public const int linearLayout4 = 2131099658;
			
			// aapt resource value: 0x7f06000d
			public const int linearLayout5 = 2131099661;
			
			// aapt resource value: 0x7f060010
			public const int linearLayout6 = 2131099664;
			
			// aapt resource value: 0x7f060013
			public const int linearLayout7 = 2131099667;
			
			// aapt resource value: 0x7f060016
			public const int linearLayout8 = 2131099670;
			
			// aapt resource value: 0x7f060019
			public const int linearLayout9 = 2131099673;
			
			// aapt resource value: 0x7f060001
			public const int textView1 = 2131099649;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050001
			public const int app_name = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int hello = 2131034112;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
